services:
  rabbitmq:
    image: 'rabbitmq:3.9-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - doc-networks

  document-management:
    build: .
    ports:
      - '8080:8080'
    links:
      - rabbitmq
    networks:
      - doc-networks
    depends_on:
      - rabbitmq
  
networks:
  doc-networks:
    driver: "bridge"

